# TODO: add your app name here
name: flutter_application_1
# TODO: add your app description here
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  go_router: ^5.0.5
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.0.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  dio: ^5.2.1+1
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.8.4
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  firebase_storage: ^11.2.5
  image_picker: ^1.0.2
  flutter_easyloading: ^3.0.5
  location: ^5.0.2+1
  geolocator: ^9.0.2
  cloud_firestore: ^4.8.4
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.4.0
  flutter_color: ^2.1.0
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_lints: ^2.0.1
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

  # for localization
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

    # intl: ^0.17.0

  flutter_gen_runner: ^5.3.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  branding: assets/images/login.png
  color_dark: "#121212"
  image_dark: assets/images/icon.png
  branding_dark: assets/images/login.png


flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    # - assets/
